# Copyright (C) 2026 swanserquack
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.



[project]
name = "study-abroad-matcher"
version = "0.1.0"
description = "Small application for finding matching courses from various universities"
readme = "README.md"
license = "AGPL-3.0-or-later"
license-files = ["LICENSE"]
requires-python = ">=3.14.0"
dependencies = [
    "beautifulsoup4==4.14.2",
    "lxml>=6.0.2",
    "lxml-stubs>=0.5.1",
    "mypy>=1.18.2",
    "orjson==3.11.4",
    "pydantic==2.12.4",
    "questionary>=2.1.1",
    "requests==2.32.5",
    "rich>=14.2.0",
    "types-html5lib>=1.1.11.20251117",
    "types-requests>=2.32.4.20250913",
]
